apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    app: eternal-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eternal-library
  template:
    metadata:
      name: eternal-library
      labels:
        app: eternal-library
    spec:
      volumes:
        - name: books-storage
          hostPath:
            path: /var/mnt/whatever/books
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - alithanar
      containers:
        - name: eternal-library
          image: ghcr.io/advplyr/audiobookshelf:2.32.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: books-storage
              mountPath: /audiobooks
              subPath: audiobooks
            - name: books-storage
              mountPath: /podcasts
              subPath: podcasts
            - name: books-storage
              mountPath: /config
              subPath: config
            - name: books-storage
              mountPath: /metadata
              subPath: metadata
      restartPolicy: Always
