apiVersion: v1
kind: Service
metadata:
  name: tailscale-frigate
  labels:
    tailscale.com/proxy-class: "irish-eyes"
  annotations:
    tailscale.com/hostname: cameras
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: frigate
  ports:
  - name: http
    port: 80
    targetPort: 5000
